name: eso_akte_sikhi
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.3.0 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  flutter: 
    sdk: flutter
  firebase_core: ^3.1.0
  cloud_firestore: ^5.0.1

dev_dependencies: 
  flutter_lints: 3.0.2
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: 'Assets/MyLogo.png'

flutter: 
  uses-material-design: true
  assets:
    - Assets/mainback.png
    - Assets/maincenter.png
    - Assets/maincenup.png
    - Assets/pencil.png
