name: eso_akte_sikhi
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.3.0 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  flutter: 
    sdk: flutter
  firebase_core: ^3.1.0
  cloud_firestore: ^5.0.1
  flutter_svg: ^2.0.10+1
  firebase_remote_config: ^5.0.1
  flutter_screenutil: ^5.9.3
  svg_path_parser: ^1.1.2

dev_dependencies: 
  flutter_lints: 3.0.2
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: 'assets/MyLogo.png'

flutter: 
  uses-material-design: true
  assets:
    - assets/
    - assets//art_objs/
    - assets/edit_bar/
    - assets/drawTools/

  fonts:
    - family: Jokerman
      fonts:
        - asset: assets/fonts/Jokerman.otf