// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0f0gVYMswefUYQtHzXMpr8FYAyCK6V60',
    appId: '1:142604141048:web:67734f10841b2b1583d60d',
    messagingSenderId: '142604141048',
    projectId: 'eso-akte-sikhi',
    authDomain: 'eso-akte-sikhi.firebaseapp.com',
    storageBucket: 'eso-akte-sikhi.appspot.com',
    measurementId: 'G-LNZBNGPPZY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBa_F_LEn0aHev_NMKJeAENrpo2j7nyNH8',
    appId: '1:142604141048:android:0a0f3f0a6c35e85783d60d',
    messagingSenderId: '142604141048',
    projectId: 'eso-akte-sikhi',
    storageBucket: 'eso-akte-sikhi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmKVCbhdYA8Bk6R-qJXXyjItIQ2bvhCTg',
    appId: '1:142604141048:ios:14e62fe86d98649283d60d',
    messagingSenderId: '142604141048',
    projectId: 'eso-akte-sikhi',
    storageBucket: 'eso-akte-sikhi.appspot.com',
    iosBundleId: 'com.arrijal.esoAkteSikhi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmKVCbhdYA8Bk6R-qJXXyjItIQ2bvhCTg',
    appId: '1:142604141048:ios:f230454a65d3acfd83d60d',
    messagingSenderId: '142604141048',
    projectId: 'eso-akte-sikhi',
    storageBucket: 'eso-akte-sikhi.appspot.com',
    iosBundleId: 'com.arrijal.esoAkteSikhi.RunnerTests',
  );
}
